openapi: 3.0.3
info:
  title: Tennis Players Stats
  description: |-
    This is a spring boot application that retrieves statistics for tennis players.
  version: 1.0.0
externalDocs:
  description: Link to the repo
  url: link
tags:
  - name: players
    description: Statistics about tennis players
paths:
  /players:
    get:
      tags:
        - players
      summary: get all players
      description: retreives all players
      operationId: getAllPlayers
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Players'          
  /players/{playerId}:
    get:
      tags:
        - players
      summary: Find players by ID
      description: Returns the player with the corresponding player id
      operationId: getPlayerById
      parameters:
        - name: playerId
          in: path
          description: Id of player to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Player'          
        '404':
          description: Player not found
  /players/statistics:
    get:
      tags:
        - players
      summary: Returns players statistics
      description: computes the country with best win ratio, average players BMI and heights median
      operationId: getStatistics
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlayersStatistics'
components:
  schemas:
    Players:
      description: List of players
      type: object
      properties:
        players:
          type: array
          items:
              $ref: '#/components/schemas/Player'
    Player:
      type: object
      properties:
        id:
          description: player's id
          type: integer
          format: int64
        firstName:
          description: player's first name
          type: string
        lastName:
          description: player's last name
          type: string
        shortName:
          description: player's short name
          type: string
        sex:
          description: player's gender
          type: string
        country:
          $ref: '#/components/schemas/Country'
        picture:
          description: player's picture link
          type: string
        data:
          $ref: '#/components/schemas/PlayerData'
    Country:
      description: player's country
      type: object
      properties:
        picture:
          description: country's picture link
          type: string
        code:
          description: country code
          type: string
    PlayerData:
      description: player's personal data
      type: object
      properties:
        rank:
          description: player's rank
          type: integer
          format: int64
        points:
          description: player's points in the last games
          type: integer
          format: int64
        weight:
          description: player's weight
          type: number
        height:
          description: player's height
          type: number
        age:
          description: player's age
          type: integer
          format: int64
        last:
          description: player's wins in last five games
          type: array
          items:
            type: integer
    PlayersStatistics:
      description: players statistics
      type: object
      properties:
        bestWinRatio:
          description: country with the best win ratio over the last five games
          type: string
        averageBMI:
          description: players average BMI
          type: number
        heightMedian:
          description: players height median
          type: number
        